apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.condor.fullnameOverride }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  type: {{ .Values.condor.service.type }}
  ports:
    - port: 22
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: {{ .Values.condor.fullnameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}