version: "3.2"
services:
  web:
    image: docker.aquaveo.com/tethys/hydraulic_structures/tethysapp-hydraulic_structures:latest
    restart: always
    depends_on:
      - "db"
      - "geoserver"
    networks:
      - "internal"
      - "external"
    ports:
      - "80:80"
    environment:
      ALLOWED_HOSTS: "127.0.0.1"
      ASGI_PROCESSES: 1
      APP_DB_HOST: "db"
      APP_DB_PORT: "5432"
      APP_DB_USERNAME: "tethys_super"
      APP_DB_PASSWORD: "pass"
      TETHYS_PUBLIC_HOST: "localhost"
      TETHYS_DB_HOST: "db"
      TETHYS_DB_USERNAME: "tethys_default"
      TETHYS_DB_PASSWORD: "pass"
      TETHYS_DB_SUPERUSER: "tethys_super"
      TETHYS_DB_SUPERUSER_PASS: "pass"
      POSTGRES_PASSWORD: "pass"
      TETHYS_DB_PORT: "5432"
      TETHYS_GS_USERNAME: "admin"
      TETHYS_GS_PASSWORD: "geoserver"
      TETHYS_GS_PROTOCOL: 'http'
      TETHYS_GS_HOST: "geoserver"
      TETHYS_GS_PORT: "8181"
      TETHYS_GS_HOST_PUB: "localhost"
      TETHYS_GS_PORT_PUB: "8181"
      TETHYS_GS_PROTOCOL_PUB: "http"
      TETHYS_CLUSTER_IP: "condor"
      TETHYS_CLUSTER_USERNAME: "condor"
      TETHYS_CLUSTER_PKEY_PASSWORD: "hydraulic_structures"
      CONDOR_PRIVATE_KEY: "/usr/lib/tethys/keys/condorkey"
    volumes:
      - type: bind
        source: /var/lib/hydraulic_structures/workspaces
        target: /var/lib/tethys_persist/workspaces
      - type: bind
        source: /var/lib/hydraulic_structures/keys
        target: /tmp/keys
  db:
    image: mdillon/postgis:latest
    restart: always
    networks:
      - "internal"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - type: bind
        source: /var/lib/hydraulic_structures/db
        target: /var/lib/postgresql/data
  geoserver:
    image: ciwater/geoserver:latest
    restart: always
    networks:
      - "internal"
      - "external"
    ports:
      - "8181:8181"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    environment:
      ENABLED_NODES: '4'
      REST_NODES: '1'
      MAX_MEMORY: '1024'
      MIN_MEMORY: '512'
      NUM_CORES: '8'
      MAX_TIMEOUT: '60'
  condor:
    image: docker.aquaveo.com/tethys/hydraulic_structures/hydraulic_structures-condor:latest
    restart: always
    networks:
      - "internal"
    ports:
      - "22:22"
    volumes:
      - type: bind
        source: /var/lib/hydraulic_structures/keys
        target: /var/lib/condor/keys
networks:
  internal:
    internal: true
  external:

